Attempted fix

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -11,6 +11,10 @@ inputs:
   key:
     description: 'SSH private key without a password for resources.ovirt.org'
     required: true
+  port:
+    description: 'Port to use for SSH connection'
+    required: false
+    default: 22
   source:
     description: 'Files to upload. This parameter allows globbing.'
     required: true
@@ -39,6 +43,7 @@ runs:
         TARGET: ${{ inputs.target }}
         CLEANUP: ${{ inputs.cleanup }}
         KEEP_FILES_COUNT: ${{ inputs.keep_files_count }}
+        PORT: ${{ inputs.port }}
       run: |
         set -x
         echo "::add-mask::${USERNAME}"
@@ -65,6 +70,10 @@ runs:
         fi
         if ! [[ "${KEEP_FILES_COUNT}" !~ ^([0-9]+)$ ]]; then
           echo -e "\e033[31;0mThe value provided to 'keep_files_count' is invalid, must be a positive number.\e033[0m" >&2 
+          exit 128
+        fi
+        if ! [[ "${PORT}" !~ ^([0-9]+)$ ]]; then
+          echo -e "\e033[31;0mThe value provided to 'port' is invalid, must be a positive number.\e033[0m" >&2 
           exit 128
         fi
     - name: "Extract SSH key"
@@ -97,12 +106,13 @@ runs:
         TARGET: ${{ inputs.target }}
         CLEANUP: ${{ inputs.cleanup }}
         KEEP_FILES_COUNT: ${{ inputs.keep_files_count }}
+        PORT: ${{ inputs.port }}
       shell: bash
       run: |
         set -x
         echo "::add-mask::${USERNAME}"
         echo "::add-mask::${KEY}"
-        scp -r -i ~/.ssh/id_rsa.sshupload "${SOURCE}" "${USERNAME}@${HOST}:${TARGET}"
+        scp -r -P "${PORT}" -i ~/.ssh/id_rsa.sshupload "${SOURCE}" "${USERNAME}@${HOST}:${TARGET}"
     - name: "Cleanup"
       env:
         # We add the parameters as environment variables, so they can be properly quoted in the shell code below.
