Fixed Dockerfile

diff --git a/.github/workflows/selftest.yml b/.github/workflows/selftest.yml
--- a/.github/workflows/selftest.yml
+++ b/.github/workflows/selftest.yml
@@ -21,7 +21,13 @@ jobs:
           docker build -t sshd test
           CONTAINER_ID=$(docker create -e "SSH_KEY=$(cat ~/.ssh/id_rsa.pub)" -p 2222:2222 sshd)
           docker start "${CONTAINER_ID}"
+          i=0
           until [ "$(docker inspect -f '{{.State.Health.Status}}' "${CONTAINER_ID}")" == "healthy" ]; do
+            let i++
+            if [ i -gt 30 ]; then
+              echo "Backing server failed to come up."
+              exit 1
+            fi
             echo "Waiting for SSH container to come up, current status is $(docker inspect -f '{{.State.Health.Status}}' "${CONTAINER_ID}")..." 
             sleep 1;
           done
